services:
  placeholder:
    image: serversideup/php:8.4.10-fpm-nginx-alpine
    restart: always
    ports:
      - "80:8080"
    volumes:
      - ./static/:/var/www/html/public/
    environment:
      - PHP_OPCACHE_ENABLE=0