name: Renovate

on:
  schedule:
    # Run once a day at midnight
    - cron: '0 0 * * *'
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          LOG_LEVEL: 'debug'